CREATE TYPE alcohol_type AS ENUM ('vodka', 'whiskey', 'gin', 'tequila', 'brandy', 'rum', 'scotch', 'bourbon', 'liqueurs', 'other');

CREATE TABLE alcohol (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  type alcohol_type NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  name VARCHAR(255) NOT NULL,
  quantity INTEGER NOT NULL
);